# Generated by Django 5.2.5 on 2025-08-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goal',
        ),
    ]
