# Generated by Django 5.2.5 on 2025-08-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_profile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='food_allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('Lose Fat', 'Lose Fat'), ('Gain Muscle', 'Gain Muscle'), ('Both', 'Both'), ('Stay Fit', 'Stay Fit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_conditions',
            field=models.CharField(choices=[('High BP', 'High BP'), ('Low BP', 'Low BP'), ('Diabetes', 'Diabetes'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
