# Generated by Django 5.2 on 2025-09-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_profile_food_allergies_profile_gender_profile_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='health_conditions',
        ),
        migrations.AddField(
            model_name='profile',
            name='health_problems',
            field=models.JSONField(blank=True, default=list, help_text='List of health problems/conditions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_health_problems',
            field=models.TextField(blank=True, help_text='Specify other health problems not listed above', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='food_allergies',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight'), ('build_muscle', 'Build Muscle'), ('improve_fitness', 'Improve Fitness')], max_length=20, null=True),
        ),
    ]
