# Generated by Django 5.2.6 on 2025-09-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_profile_health_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('exercise', 'Exercise'), ('nutrition', 'Nutrition'), ('recovery', 'Recovery'), ('lifestyle', 'Lifestyle')], default='fitness', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('maintain_weight', 'Maintain Weight'), ('build_muscle', 'Gain Muscle'), ('both', 'Gain Muscle & Lose Fat'), ('improve_fitness', 'Improve Fitness')], max_length=20, null=True),
        ),
    ]
