# Generated by Django 5.2.5 on 2025-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_doctor_add_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight_loss_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
