# Generated by Django 5.2.5 on 2025-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_profile_weight_loss_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tips/'),
        ),
    ]
