# Generated by Django 5.2 on 2025-10-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_doctor_photo_tip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary – little or no exercise'), ('lightly_active', 'Lightly Active – light exercise 1–3 days/week'), ('moderately_active', 'Moderately Active – moderate exercise 3–5 days/week'), ('very_active', 'Very Active – hard exercise 6–7 days/week'), ('extra_active', 'Extra Active – intense training or physical job')], help_text='Your current activity level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='Current weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='exercise_place',
            field=models.CharField(blank=True, choices=[('gym', 'Gym'), ('home', 'Home'), ('outdoor', 'Outdoor')], help_text='Preferred exercise location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target weight in kg', null=True),
        ),
    ]
