# Generated by Django 5.2.5 on 2025-10-08 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_profile_weight_profile_activity_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.PositiveIntegerField(default=0, help_text='Total calories consumed today')),
                ('sleep_hours', models.DecimalField(decimal_places=1, default=0, help_text='Hours of sleep', max_digits=4)),
                ('exercise_minutes', models.PositiveIntegerField(default=0, help_text='Minutes of exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
