# Generated by Django 5.2.5 on 2025-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_dailylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='exercise_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='sleep_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
