# Generated by Django 5.2.5 on 2025-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_dailylog_options_alter_dailylog_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_tracking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
