# Generated by Django 5.2.5 on 2026-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='is_ai_estimated',
            field=models.BooleanField(default=False, help_text='Whether calories were estimated by AI food recognition'),
        ),
    ]
